// <auto-generated />
namespace StudentActivity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingClubFkAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingClubFkAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031703303_AddingClubFkAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
