//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentActivity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentActivity.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string About_page {
            get {
                return ResourceManager.GetString("About page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Student&apos;s Activities.
        /// </summary>
        public static string AboutStudentsActivities {
            get {
                return ResourceManager.GetString("AboutStudentsActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Club.
        /// </summary>
        public static string Add_New_Club {
            get {
                return ResourceManager.GetString("Add New Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Program.
        /// </summary>
        public static string Add_New_Program {
            get {
                return ResourceManager.GetString("Add New Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        public static string Add_Student {
            get {
                return ResourceManager.GetString("Add Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student you are trying to register a program for him is already registered in that program..
        /// </summary>
        public static string Added_student_already_registerd_in_program {
            get {
                return ResourceManager.GetString("Added student already registerd in program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Home Page.
        /// </summary>
        public static string AdminHome {
            get {
                return ResourceManager.GetString("AdminHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create and manage all programs.
        /// </summary>
        public static string AdminHome_can_do_1 {
            get {
                return ResourceManager.GetString("AdminHome_can_do_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the student list for a program.
        /// </summary>
        public static string AdminHome_can_do_2 {
            get {
                return ResourceManager.GetString("AdminHome_can_do_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manage the eligiblity of students.
        /// </summary>
        public static string AdminHome_can_do_3 {
            get {
                return ResourceManager.GetString("AdminHome_can_do_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Manage create and manage the clubs.
        /// </summary>
        public static string AdminHome_can_do_4 {
            get {
                return ResourceManager.GetString("AdminHome_can_do_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can approve or reject any requested program from club coordinator.
        /// </summary>
        public static string AdminHome_can_do_5 {
            get {
                return ResourceManager.GetString("AdminHome_can_do_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Club you are trying to join, you are already member of it!.
        /// </summary>
        public static string Already_a_member_of_the_club {
            get {
                return ResourceManager.GetString("Already a member of the club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already registered in this program.
        /// </summary>
        public static string already_registered {
            get {
                return ResourceManager.GetString("already registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve this program?.
        /// </summary>
        public static string Approve_program_confirmation {
            get {
                return ResourceManager.GetString("Approve program confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Programs.
        /// </summary>
        public static string Available_Programs {
            get {
                return ResourceManager.GetString("Available Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified.
        /// </summary>
        public static string Certified {
            get {
                return ResourceManager.GetString("Certified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer an easy way for students who completed any program to print their Certification for these programs whenever and from wherever they want...
        /// </summary>
        public static string CertifiedIntro {
            get {
                return ResourceManager.GetString("CertifiedIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a program to register in.
        /// </summary>
        public static string Choose_a_program_to_register {
            get {
                return ResourceManager.GetString("Choose a program to register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Club you are trying to add is already Exist!.
        /// </summary>
        public static string Club_already_Exist {
            get {
                return ResourceManager.GetString("Club already Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Name.
        /// </summary>
        public static string Club_Name {
            get {
                return ResourceManager.GetString("Club Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Vision in Arabic.
        /// </summary>
        public static string Club_Vision_in_Arabic {
            get {
                return ResourceManager.GetString("Club Vision in Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Vision in English.
        /// </summary>
        public static string Club_Vision_in_English {
            get {
                return ResourceManager.GetString("Club Vision in English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Coordinator.
        /// </summary>
        public static string ClubCoordinator {
            get {
                return ResourceManager.GetString("ClubCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Coordinator Home Page.
        /// </summary>
        public static string ClubCorHome {
            get {
                return ResourceManager.GetString("ClubCorHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Request programs that can be approved later by the admin.
        /// </summary>
        public static string ClubCorHome_can_do_1 {
            get {
                return ResourceManager.GetString("ClubCorHome_can_do_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string ClubId {
            get {
                return ResourceManager.GetString("ClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Programs.
        /// </summary>
        public static string CompletedPrograms {
            get {
                return ResourceManager.GetString("CompletedPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        public static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We keep in touch with students through our website by providing a special page to show the latest news in the university...
        /// </summary>
        public static string ConnectivityIntro {
            get {
                return ResourceManager.GetString("ConnectivityIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string Contact_page {
            get {
                return ResourceManager.GetString("Contact page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string Coordinator {
            get {
                return ResourceManager.GetString("Coordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string Create_a_new_account_ {
            get {
                return ResourceManager.GetString("Create a new account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a List of the Current Provided Programs:.
        /// </summary>
        public static string CurrentProgramsList {
            get {
                return ResourceManager.GetString("CurrentProgramsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete field.
        /// </summary>
        public static string Delete_field {
            get {
                return ResourceManager.GetString("Delete field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Program.
        /// </summary>
        public static string Delete_Program {
            get {
                return ResourceManager.GetString("Delete Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Program ?.
        /// </summary>
        public static string Delete_Program_Confirmation {
            get {
                return ResourceManager.GetString("Delete Program Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Club?.
        /// </summary>
        public static string DeleteClubConfirmation {
            get {
                return ResourceManager.GetString("DeleteClubConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this field ?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahmed, Developer.
        /// </summary>
        public static string DeveloperAhmed {
            get {
                return ResourceManager.GetString("DeveloperAhmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone, Developer.
        /// </summary>
        public static string DeveloperSomeone {
            get {
                return ResourceManager.GetString("DeveloperSomeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohammed, Developing leader.
        /// </summary>
        public static string DevelopingLeaderMohammed {
            get {
                return ResourceManager.GetString("DevelopingLeaderMohammed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Program.
        /// </summary>
        public static string EditProgram {
            get {
                return ResourceManager.GetString("EditProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Student Name:.
        /// </summary>
        public static string Enter_Student_Name {
            get {
                return ResourceManager.GetString("Enter Student Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date of the program:.
        /// </summary>
        public static string Enter_the_date_of_the_program {
            get {
                return ResourceManager.GetString("Enter the date of the program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the lecturer name:.
        /// </summary>
        public static string Enter_the_lecturer_name {
            get {
                return ResourceManager.GetString("Enter the lecturer name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title of the program:.
        /// </summary>
        public static string Enter_the_title_of_the_program {
            get {
                return ResourceManager.GetString("Enter the title of the program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string Error_occured {
            get {
                return ResourceManager.GetString("Error occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string External_login_removed {
            get {
                return ResourceManager.GetString("External login removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Programs.
        /// </summary>
        public static string FinishedPrograms {
            get {
                return ResourceManager.GetString("FinishedPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Work.
        /// </summary>
        public static string HardWork {
            get {
                return ResourceManager.GetString("HardWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting more effort on developing our services to serve students in an easy way...
        /// </summary>
        public static string HardWorkIntro {
            get {
                return ResourceManager.GetString("HardWorkIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string Invalid_code {
            get {
                return ResourceManager.GetString("Invalid code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string Invalid_login {
            get {
                return ResourceManager.GetString("Invalid login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Eligible.
        /// </summary>
        public static string IsEligible {
            get {
                return ResourceManager.GetString("IsEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a Club.
        /// </summary>
        public static string Join_Club {
            get {
                return ResourceManager.GetString("Join Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUC.
        /// </summary>
        public static string JUC {
            get {
                return ResourceManager.GetString("JUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jubail University College Activities Website.
        /// </summary>
        public static string JUC_Activities_Website {
            get {
                return ResourceManager.GetString("JUC Activities Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Website is going to allow the student to register for programs, and print them later on..
        /// </summary>
        public static string JUC_intro {
            get {
                return ResourceManager.GetString("JUC intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUCGate.
        /// </summary>
        public static string JUCGate {
            get {
                return ResourceManager.GetString("JUCGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Main Gate of JUC.
        /// </summary>
        public static string JUCGateBody {
            get {
                return ResourceManager.GetString("JUCGateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Club.
        /// </summary>
        public static string Leave_Club {
            get {
                return ResourceManager.GetString("Leave Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this club.
        /// </summary>
        public static string leave_this_club {
            get {
                return ResourceManager.GetString("leave this club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string local_account_to_log_in {
            get {
                return ResourceManager.GetString("local account to log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string Log_Off {
            get {
                return ResourceManager.GetString("Log Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love.
        /// </summary>
        public static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying our best to provide whatever students want depending on their wishes...
        /// </summary>
        public static string LoveIntro {
            get {
                return ResourceManager.GetString("LoveIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Student Number.
        /// </summary>
        public static string MaximumStudentNumber {
            get {
                return ResourceManager.GetString("MaximumStudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION.
        /// </summary>
        public static string MISSION {
            get {
                return ResourceManager.GetString("MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to make Student&apos;s life easier and funnier..
        /// </summary>
        public static string MISSIONBody {
            get {
                return ResourceManager.GetString("MISSIONBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No..
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        public static string Mobility {
            get {
                return ResourceManager.GetString("Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide many services through our website to make student&apos;s life easier...
        /// </summary>
        public static string MobilityIntro {
            get {
                return ResourceManager.GetString("MobilityIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available programs.
        /// </summary>
        public static string No_available_programs {
            get {
                return ResourceManager.GetString("No available programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Are no pending programs.
        /// </summary>
        public static string No_pending_programs {
            get {
                return ResourceManager.GetString("No pending programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no programs registered yet!.
        /// </summary>
        public static string No_programs_registered {
            get {
                return ResourceManager.GetString("No programs registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no student registered in this program.
        /// </summary>
        public static string No_student_registered {
            get {
                return ResourceManager.GetString("No student registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not completed any programs yet!.
        /// </summary>
        public static string NoCompletedPrograms {
            get {
                return ResourceManager.GetString("NoCompletedPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Values.
        /// </summary>
        public static string OurValues {
            get {
                return ResourceManager.GetString("OurValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string Password_has_been_changed {
            get {
                return ResourceManager.GetString("Password has been changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string Password_has_been_set {
            get {
                return ResourceManager.GetString("Password has been set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: (Requires one Capital letter, one small letter, one special character and numbers).
        /// </summary>
        public static string Password_Register {
            get {
                return ResourceManager.GetString("Password Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Programs.
        /// </summary>
        public static string Pending_Programs {
            get {
                return ResourceManager.GetString("Pending Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Status.
        /// </summary>
        public static string Pending_Status {
            get {
                return ResourceManager.GetString("Pending Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string Phone_number_added {
            get {
                return ResourceManager.GetString("Phone number added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string Phone_number_removed {
            get {
                return ResourceManager.GetString("Phone number removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Certificate.
        /// </summary>
        public static string PrintCertificate {
            get {
                return ResourceManager.GetString("PrintCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program you are 
        ///trying to add is already added.
        /// </summary>
        public static string Program_already_added {
            get {
                return ResourceManager.GetString("Program already added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program in the MPH.
        /// </summary>
        public static string ProgramBody {
            get {
                return ResourceManager.GetString("ProgramBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Details.
        /// </summary>
        public static string ProgramDetails {
            get {
                return ResourceManager.GetString("ProgramDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Form.
        /// </summary>
        public static string ProgramForm {
            get {
                return ResourceManager.GetString("ProgramForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide different kinds of programs such as courses, out-side visits, and activities...
        /// </summary>
        public static string ProgramsOfferedIntro {
            get {
                return ResourceManager.GetString("ProgramsOfferedIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Programs.
        /// </summary>
        public static string Registered_Programs {
            get {
                return ResourceManager.GetString("Registered Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register in Program.
        /// </summary>
        public static string RegisterInProgram {
            get {
                return ResourceManager.GetString("RegisterInProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this program?.
        /// </summary>
        public static string Reject_program_confirmation {
            get {
                return ResourceManager.GetString("Reject program confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Status.
        /// </summary>
        public static string Remove_Status {
            get {
                return ResourceManager.GetString("Remove Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Programs.
        /// </summary>
        public static string Request_Programs {
            get {
                return ResourceManager.GetString("Request Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Programs.
        /// </summary>
        public static string Requested_Programs {
            get {
                return ResourceManager.GetString("Requested Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve a program.
        /// </summary>
        public static string Retrieve_a_program {
            get {
                return ResourceManager.GetString("Retrieve a program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program you are 
        ///trying to retrieve is already avaliable.
        /// </summary>
        public static string Retrieve_program_already_available {
            get {
                return ResourceManager.GetString("Retrieve program already available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program you are 
        ///trying to retrieve does not exist.
        /// </summary>
        public static string Retrieve_program_not_exist {
            get {
                return ResourceManager.GetString("Retrieve program not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Club.
        /// </summary>
        public static string Select_a_Club {
            get {
                return ResourceManager.GetString("Select a Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Program.
        /// </summary>
        public static string Select_a_Program {
            get {
                return ResourceManager.GetString("Select a Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This Website is Made for JUC Students By JUC Students. We Are so happy with this result!&quot;.
        /// </summary>
        public static string Slider1 {
            get {
                return ResourceManager.GetString("Slider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;One word... WOW!!&quot;.
        /// </summary>
        public static string Slider2 {
            get {
                return ResourceManager.GetString("Slider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Could I... BE any more happy with this Achievement?&quot;.
        /// </summary>
        public static string Slider3 {
            get {
                return ResourceManager.GetString("Slider3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already registered in this program.
        /// </summary>
        public static string Student_already_registered_in_program {
            get {
                return ResourceManager.GetString("Student already registered in program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Id.
        /// </summary>
        public static string Student_Id {
            get {
                return ResourceManager.GetString("Student Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string Student_Name {
            get {
                return ResourceManager.GetString("Student Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student has not registered in the website yet!.
        /// </summary>
        public static string Student_not_registerd_in_website {
            get {
                return ResourceManager.GetString("Student not registerd in website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s Activity.
        /// </summary>
        public static string Student_s_Activity {
            get {
                return ResourceManager.GetString("Student\'s Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Best Way To Make Student&apos;s Life More Interesting!!.
        /// </summary>
        public static string StudentActivityShortIntro {
            get {
                return ResourceManager.GetString("StudentActivityShortIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Home.
        /// </summary>
        public static string StudentHome {
            get {
                return ResourceManager.GetString("StudentHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can register in any available program.
        /// </summary>
        public static string StudentHome_can_do_1 {
            get {
                return ResourceManager.GetString("StudentHome_can_do_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view all registered programs.
        /// </summary>
        public static string StudentHome_can_do_2 {
            get {
                return ResourceManager.GetString("StudentHome_can_do_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can join a club.
        /// </summary>
        public static string StudentHome_can_do_3 {
            get {
                return ResourceManager.GetString("StudentHome_can_do_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can print a certificate for any completed program.
        /// </summary>
        public static string StudentHome_can_do_4 {
            get {
                return ResourceManager.GetString("StudentHome_can_do_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students List.
        /// </summary>
        public static string Students_List {
            get {
                return ResourceManager.GetString("Students List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s Activities is a part of the Student&apos;s Affairs, which is a department of the university that serves as the gate between the student and the academic departments..
        /// </summary>
        public static string StudentsActivitiesIntro {
            get {
                return ResourceManager.GetString("StudentsActivitiesIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main goal of Student&apos;s Activities is to make the lives of the students easier and more interesting while they are studying at the university by providing special programs such as courses, visits, and activities that support the students in their studies.
        /// </summary>
        public static string StudentsActivitiesMainGoal {
            get {
                return ResourceManager.GetString("StudentsActivitiesMainGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string Two_factor_authentication_provider_has_been_set {
            get {
                return ResourceManager.GetString("Two-factor authentication provider has been set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string Verify_phone_failed {
            get {
                return ResourceManager.GetString("Verify phone failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISION.
        /// </summary>
        public static string VISION {
            get {
                return ResourceManager.GetString("VISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our vision is to graduate qualified students with both academic and communicate skills that will help them to succeed in their own lives..
        /// </summary>
        public static string VISIONBody {
            get {
                return ResourceManager.GetString("VISIONBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Site Visit done by Civil Club.
        /// </summary>
        public static string VisitBody {
            get {
                return ResourceManager.GetString("VisitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Mark a Certificate.
        /// </summary>
        public static string Water_Mark_Certificate {
            get {
                return ResourceManager.GetString("Water Mark Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatWeOffer.
        /// </summary>
        public static string WhatWeOffer {
            get {
                return ResourceManager.GetString("WhatWeOffer", resourceCulture);
            }
        }
    }
}
